param([string]$Root = (Split-Path -Parent $PSScriptRoot))

$ErrorActionPreference = 'Stop'
$manifest = Get-Content -LiteralPath (Join-Path $Root 'data\publishing.json') -Raw -Encoding utf8 | ConvertFrom-Json -DateKind String
$errors = [Collections.Generic.List[string]]::new()
$registered = @{}

foreach ($article in $manifest.articles) {
  $registered[$article.file] = $true
  foreach ($field in @('file','headline','description','image','imageCredit','published','modified','eventDate','section','location')) {
    if ([string]::IsNullOrWhiteSpace([string]$article.$field)) {
      $errors.Add("$($article.file): missing required publishing field '$field'.")
    }
  }
  if (@($article.sourceUrls).Count -eq 0) {
    $errors.Add("$($article.file): at least one verification source URL is required.")
  }
  try { [void][DateTimeOffset]::Parse($article.eventDate, [Globalization.CultureInfo]::InvariantCulture) }
  catch { $errors.Add("$($article.file): eventDate is not a valid date.") }
  $gridMode = if ([string]::IsNullOrWhiteSpace([string]$article.gridMode)) { 'event' } else { [string]$article.gridMode }
  if ($gridMode -notin @('event','publication')) {
    $errors.Add("$($article.file): gridMode must be 'event' or 'publication'.")
  }
  $publishedGridDate = try {
    [DateTimeOffset]::Parse($article.published, [Globalization.CultureInfo]::InvariantCulture).ToString('yyyy-MM-dd')
  } catch {
    $errors.Add("$($article.file): published is not a valid date.")
    ''
  }

  $articlePath = Join-Path $Root $article.file
  $imagePath = Join-Path $Root $article.image
  if (-not (Test-Path -LiteralPath $articlePath)) {
    $errors.Add("$($article.file): article file does not exist.")
    continue
  }
  if (-not (Test-Path -LiteralPath $imagePath)) {
    $errors.Add("$($article.file): representative image does not exist: $($article.image)")
  }
  if (-not [string]::IsNullOrWhiteSpace([string]$article.homepageImage)) {
    $homepageImagePath = Join-Path $Root $article.homepageImage
    if (-not (Test-Path -LiteralPath $homepageImagePath)) {
      $errors.Add("$($article.file): homepage image does not exist: $($article.homepageImage)")
    }
  }

  $content = Get-Content -LiteralPath $articlePath -Raw -Encoding utf8
  foreach ($needle in @('id="imnews-newsarticle"','"@type":"NewsArticle"','"datePublished":"','<time datetime="','IM News Editorial Desk')) {
    if (-not $content.Contains($needle)) {
      $errors.Add("$($article.file): generated publishing output is incomplete ($needle).")
    }
  }
  $publishedMatch = [regex]::Match($content, '"datePublished":"([^"]+)"')
  if ($publishedMatch.Success) {
    try {
      $manifestPublished = [DateTimeOffset]::Parse([string]$article.published, [Globalization.CultureInfo]::CurrentCulture)
      $articlePublished = [DateTimeOffset]::Parse($publishedMatch.Groups[1].Value, [Globalization.CultureInfo]::InvariantCulture)
      if ($manifestPublished -ne $articlePublished) {
        $errors.Add("$($article.file): generated datePublished does not match the publishing manifest.")
      }
    } catch {
      $errors.Add("$($article.file): generated datePublished is not a valid date.")
    }
  }
  if ($content -match '<div\s+class="article-byline"[^>]*data-edit-id=') {
    $errors.Add("$($article.file): generated byline must not be overwritten by the legacy translation editor.")
  }
  if (([regex]::Matches($content, '<meta\s+name="description"')).Count -ne 1) {
    $errors.Add("$($article.file): must contain exactly one meta description.")
  }
  if (([regex]::Matches($content, '<link\s+rel="canonical"')).Count -ne 1) {
    $errors.Add("$($article.file): must contain exactly one canonical link.")
  }
  foreach ($name in @($article.correspondents) + @($article.photographers)) {
    if (-not $content.Contains($name)) {
      $errors.Add("$($article.file): credit name '$name' is not visible in the article.")
    }
  }

  $sectionFile = if ($article.section -eq 'Sports') { 'sports.html' } elseif ($article.section -eq 'Culture') { 'culture.html' } else { $null }
  if ($sectionFile) {
    $sectionContent = Get-Content -LiteralPath (Join-Path $Root $sectionFile) -Raw -Encoding utf8
    $articleFilePattern = [regex]::Escape($article.file)
    $cardPattern = '(?is)<div\s+class="story-card"(?<attrs>[^>]*)>(?:(?!<div\s+class="story-card").)*?href="' + $articleFilePattern + '(?:[?#][^"]*)?"'
    $cardMatch = [regex]::Match($sectionContent, $cardPattern)
    if (-not $cardMatch.Success) {
      $errors.Add("$($article.file): no matching card was found in $sectionFile.")
    } elseif ($cardMatch.Groups['attrs'].Value -notmatch ('data-event-date="' + [regex]::Escape($article.eventDate) + '"')) {
      $errors.Add("$($article.file): $sectionFile event date must match eventDate $($article.eventDate).")
    } elseif ($gridMode -eq 'publication' -and $cardMatch.Groups['attrs'].Value -notmatch ('data-published-date="' + [regex]::Escape($publishedGridDate) + '"[^>]*data-grid-mode="publication"')) {
      $errors.Add("$($article.file): $sectionFile must use publication-date grid ordering for $publishedGridDate.")
    }
  }

  $homeContent = Get-Content -LiteralPath (Join-Path $Root 'index.html') -Raw -Encoding utf8
  $homeCardPattern = '(?is)<div\s+class="story-card"(?<attrs>[^>]*)>(?:(?!<div\s+class="story-card").)*?href="' + [regex]::Escape($article.file) + '(?:[?#][^"]*)?"'
  $homeCardMatch = [regex]::Match($homeContent, $homeCardPattern)
  if ($homeCardMatch.Success -and $homeCardMatch.Groups['attrs'].Value -notmatch ('data-event-date="' + [regex]::Escape($article.eventDate) + '"')) {
    $errors.Add("$($article.file): homepage event date must match eventDate $($article.eventDate).")
  } elseif ($homeCardMatch.Success -and $gridMode -eq 'publication' -and $homeCardMatch.Groups['attrs'].Value -notmatch ('data-published-date="' + [regex]::Escape($publishedGridDate) + '"[^>]*data-grid-mode="publication"')) {
    $errors.Add("$($article.file): homepage must use publication-date grid ordering for $publishedGridDate.")
  }
}

$latestArticle = $manifest.articles |
  Sort-Object { [DateTimeOffset]::Parse($_.published, [Globalization.CultureInfo]::InvariantCulture) } -Descending |
  Select-Object -First 1
if ($latestArticle) {
  $homeContent = Get-Content -LiteralPath (Join-Path $Root 'index.html') -Raw -Encoding utf8
  $heroPattern = '(?is)<a\s+href="' + [regex]::Escape($latestArticle.file) + '"\s+style="text-decoration:none;">\s*<div\s+class="hero-story">'
  if ($homeContent -notmatch $heroPattern) {
    $errors.Add("Homepage lead must be the latest published article: $($latestArticle.file).")
  }
  $leadImage = if ([string]::IsNullOrWhiteSpace([string]$latestArticle.homepageImage)) { [string]$latestArticle.image } else { [string]$latestArticle.homepageImage }
  if ($homeContent -notmatch ('(?is)<img\s+src="' + [regex]::Escape($leadImage) + '"[^>]*data-edit-id="home-hero-image"')) {
    $errors.Add("Homepage lead image must match the configured homepage image: $leadImage.")
  }
  $breakingText = if ([string]::IsNullOrWhiteSpace([string]$latestArticle.breakingText)) { $latestArticle.description } else { [string]$latestArticle.breakingText }
  if (-not $homeContent.Contains("data-edit-id=`"home-breaking-text`" data-edit-type=`"text`">$breakingText</span>")) {
    $errors.Add("Homepage breaking ticker must describe the latest published article: $($latestArticle.file).")
  }
}

Get-ChildItem -LiteralPath $Root -File -Filter 'article-*.html' | ForEach-Object {
  if ($_.BaseName -match '^article-(\d+)$') {
    $number = [int]$Matches[1]
    if ($number -ge [int]$manifest.managedFromArticle -and -not $registered.ContainsKey($_.Name)) {
      $errors.Add("$($_.Name): new articles must be registered in data/publishing.json.")
    }
  }
}

if ($errors.Count -gt 0) {
  $errors | ForEach-Object { Write-Error $_ }
  throw "Publishing validation failed with $($errors.Count) error(s)."
}

Write-Output "Publishing validation passed for $(@($manifest.articles).Count) managed articles."
